export * from '@/pages/admin/dashboard';
export * from '@/pages/order';
export * from '@/pages/order/detail';
export * from '@/pages/product';
export * from '@/pages/admin/customers';
export * from '@/pages/admin/addproducts';
export * from '@/pages/product/updateproduct';
export * from '@/pages/category';
export * from '@/pages/statistic';
